env: local

http:
  port: 3000

base_domain: http://localhost

db:
  name: hex_fwk_db_test
  schema: hex_fwk
  host: localhost
  port: 5433
  user: hex_fwk_db_user
  pass: hex_fwk_db_pass_test

version: 0.0.1